kind: pipeline
name: default

steps:
- name: docker-cpu
  image: plugins/docker
  when:
    event: [ push, pull_request ]
    status: success
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quay.io/dotmesh/jupyterlab-tensorflow
    registry: quay.io   
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BRANCH}
    dockerfile: Dockerfile.cpu
- name: docker-gpu
  image: plugins/docker
  when:
    event: [ push, pull_request ]
    status: success
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quay.io/dotmesh/jupyterlab-tensorflow-gpu
    registry: quay.io   
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BRANCH}
    dockerfile: Dockerfile.gpu
- name: docker-cpu-tag
  image: plugins/docker
  when:
    event: tag 
    status: success
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quay.io/dotmesh/jupyterlab-tensorflow
    registry: quay.io
    tags:
      - ${DRONE_TAG}
    dockerfile: Dockerfile.cpu
- name: docker-gpu-tag
  image: plugins/docker
  when:
    event: tag 
    status: success
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quay.io/dotmesh/jupyterlab-tensorflow-gpu
    registry: quay.io  
    when:
      event: tag 
      status: success
    tags:
      - ${DRONE_TAG}
    dockerfile: Dockerfile.gpu
- name: trigger-e2e
  image: arwineap/docker-alpine-toolbox:latest
  environment:
    E2E_TRIGGER_TOKEN:
      from_secret: e2e_trigger_token
  when:
    event: [ push, pull_request ]
    status: success
  depends_on:
    - docker-gpu
    - docker-cpu
  commands:
    - id=$(curl -X POST -F "token=$${E2E_TRIGGER_TOKEN}" -F "ref=master" -F "variables[CI_SERVICE_BEING_TESTED]=jupyterlab-tensorflow" -F "variables[CI_DOCKER_TAG]=$DRONE_COMMIT" -F "variables[DOTMESH_CI_BUILD_REF_NAME]=$DRONE_COMMIT_BRANCH" -F "variables[RELEASE_TAG]=latest" https://gitlab.dotmesh.com/api/v4/projects/66/trigger/pipeline | jq .id)
    - echo "Triggered successfully, pipeline - https://gitlab.dotmesh.com/dotmesh/e2e-firecracker-sync/pipelines/$${id}"
    - id=$(curl -X POST -F "token=$${E2E_TRIGGER_TOKEN}" -F "ref=master" -F "variables[CI_SERVICE_BEING_TESTED]=jupyterlab-tensorflow-gpu" -F "variables[CI_DOCKER_TAG]=$DRONE_COMMIT" -F "variables[DOTMESH_CI_BUILD_REF_NAME]=$DRONE_COMMIT_BRANCH" -F "variables[RELEASE_TAG]=latest" https://gitlab.dotmesh.com/api/v4/projects/66/trigger/pipeline | jq .id)
    -  echo "Triggered successfully, pipeline - https://gitlab.dotmesh.com/dotmesh/e2e-firecracker-sync/pipelines/$${id}"
- name: slack
  image: plugins/slack
  when:
    status: [ success, failure ]
  depends_on:
    - trigger-e2e
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg
